// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBccJe0Se4LHf1ojmr0z_SqRZdOviZpzAs',
    appId: '1:293869352804:web:95fa88426cbbf451602c71',
    messagingSenderId: '293869352804',
    projectId: 'kwaapp',
    authDomain: 'kwaapp.firebaseapp.com',
    databaseURL: 'https://kwaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kwaapp.appspot.com',
    measurementId: 'G-NBP5PJDSE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHi9J9KgbiIxpCsgvnoio8GoijZ3Txvxw',
    appId: '1:293869352804:android:83a84bba2e680afd602c71',
    messagingSenderId: '293869352804',
    projectId: 'kwaapp',
    databaseURL: 'https://kwaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kwaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR4yjFvUKQzKtuly0aesYP7ykFEL7Rnt0',
    appId: '1:293869352804:ios:77365937ffc9e903602c71',
    messagingSenderId: '293869352804',
    projectId: 'kwaapp',
    databaseURL: 'https://kwaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kwaapp.appspot.com',
    iosBundleId: 'com.example.kwaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR4yjFvUKQzKtuly0aesYP7ykFEL7Rnt0',
    appId: '1:293869352804:ios:6f979eb446e73177602c71',
    messagingSenderId: '293869352804',
    projectId: 'kwaapp',
    databaseURL: 'https://kwaapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kwaapp.appspot.com',
    iosBundleId: 'com.example.kwaApp.RunnerTests',
  );
}
